# Air config for hot-reload in development
root = "."
tmp_dir = "tmp"

[build]
cmd = "/usr/local/go/bin/go build -trimpath -buildvcs=false -o ./tmp/app ./cmd/api"
bin = "./tmp/app"
send_interrupt = true
kill_delay = "500ms"
stop_on_error = true
log = "build"

# File watching rules
include_ext = ["go", "sql", "yaml", "yml", "toml", "env", "tpl", "tmpl", "html", "sh"]
exclude_dir = [
  "tmp", "vendor", ".git", "build", "docs", "dist", "internal/tests", "scripts"
]
exclude_regex = ["_test\\.go$"]
follow_symlink = true

[log]
time = true

[screen]
clear_on_rebuild = true

[misc]
clean_on_exit = true

[hooks]
pre_build = ["sh -lc ./scripts/sqlc-if-needed.sh"]
