services:
  pg_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gostartkit
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: gostartkit
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gostartkit -d gostartkit"]
      interval: 3s
      timeout: 2s
      retries: 20

  redis_test:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "56379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 20

